### ISSUE TITLE
No such device or address

### ISSUE THREAD

**Issue by chinasteel** [moosefs/moosefs#148] opened 2018-11-01 09:03 UTC
I can't open my file when I execute 'mfsmaster -a',  It report error that 'No such device or address'. please help me

![_20181101170204](https://user-images.githubusercontent.com/7941369/47842529-e5640c80-ddf7-11e8-90b2-1463b536718a.png)

**Comment by oxide94** [comment] 2018-11-01 17:04
Hello, can you please tell us more information about your cluster? What version of Master Server, Chunkservers and Client are you using? Can you please execute `mfsmount -V`? Can you please provide us with exact steps on how to reproduce the issue?

**Comment by chinasteel** [comment] 2018-11-02 02:39
@oxide94 thanks, my system infomation:

Master Server, Chunkservers version : 2.0.66-1
---------------------------------------------------
client :
MFS version 2.0.66-1
FUSE library version: 2.8.3
fusermount version: 2.9.3

ps : It's difficult to reproduce , and i can provide below infomation only , thanks
1. we found master is down , and our operator use mfsmetalogger as master
2. we found some file is lost , then operator execute mfsmaster -a on mfsmetalogger system(now is master, he think the metadata and changelog is newer )
3. when step 2 execute after , the lost file can see but the problem is happen .

**Comment by xandrus** [comment] 2018-11-02 08:35
Hi,
Basically, MooseFS 2.0 is no longer supported.
https://moosefs.com/support/#moosefs-support-status

We strongly recommend to update MooseFS to latest stable version 3.0.101.

I would like to also mention that Fuse libraries and Linux kernel ware also released in newer version with a lot of improvements and bug fixes. Please consider upgrading your current configuration.

By the way, this is our changelog so you can see what was made since MooseFS version 2.0.66 :
https://github.com/moosefs/moosefs/blob/master/debian/changelog

**Comment by oxide94** [comment] 2018-11-02 10:45
@chinasteel:
The solution is exactly what @xandrus said. Please upgrade to MooseFS 3.x as soon as possible. Your current MooseFS version 2.0.66-1 was released over 3.5 years ago (on May 8th, 2015) - many bugs have been fixed and many improvements have been done since then.

Upgrade process from MooseFS 2.x to MooseFS 3.x is a simple process, but the most important is order of the upgrade. It is as simple as upgrade between minor versions (e.g. between 3.0.100 and 3.0.101). The most important is to **1) backup `metadata.mfs` file after stopping Master Server** and 2) to do the upgrade in a proper order:

1. MooseFS Tools (CGI, CGI Server, CLI etc.)
2. MooseFS Master Server
3. MooseFS Metaloggers
4. MooseFS Chunkservers (one-by-one)
5. MooseFS Clients (when the rest of the cluster is upgraded). Client upgrade requires to stop all processes using this client and unmount the client then, `lsof -n | grep /mnt/mfs` may be helpful here.

You can find more information on how to perform the upgrade in "MooseFS Upgrade Guide", Chapter 2: "MooseFS upgrade to newer version", p. 5. You can obtain it from: https://moosefs.com/support

In case of any questions regarding the upgrade, please don't hesitate to ask. Good luck! :)

Best,
Peter / MooseFS Team

**Comment by chinasteel** [comment] 2018-11-02 10:59
ok, thanks all @xandrus  @oxide94 . I will try later.

**Comment by oxide94** [comment] 2018-11-02 11:01
@chinasteel: Sure, no problem :) We strongly recommend to do that, please do not worry as the upgrade is seamless and easy.

Best,
Peter / MooseFS Team

**Closed by oxide94** 2018-11-02 11:02 UTC

**Comment by joej** [comment] 2022-03-09 19:36
Literally, this is happening to me
**mfsfileinfo /mfs/somedir/f9/6197fa6541a477a3aea7bcf9.json**
```
	chunk 0: 000000000035CA67_00000001 / (id:3525223 ver:1)
		no valid copies !!!

```
Yet ...when I look into each of the 4 chunkservers
via ansible find command for  \*000000000035CA67_00000001\*

> chunkserver 1 = /mfs/chunks1/EB/chunk_000000000035CA67_00000001.mfs
> chunkserver2 = /mfs/chunks1/EE/chunk_000000000035CA67_00000001.mfs

They exist and have content in them.

**Comment by chogata** [comment] 2022-03-10 14:23
@joej - do I understand correctly, that you executed the "mfsfileinfo" command while chunkservers were not running? If yes, then the message from "mfsfileinfo" is completely valid - master cannot find valid copies if chunkservers with those copies are not connected. It doesn't matter that the files with chunks exist on chunkservers' hard drives - if the chunkservers itself aren't running, the master has no access to chunks, therefore it replies "no valid copies".
