### ISSUE TITLE
mfsmount showing wrong version of files

### ISSUE THREAD

**Issue by ghost** [moosefs/moosefs#89] opened 2018-01-16 22:10 UTC
Hello, 

Files do not always update through the mfsmount point in certain cases. This especially happens when a file is updated, but the name does not change. For example, an index.html file. 

I can duplicate the issue by running this test. All systems are running 3.0.99 on FreeBSD 11.1. Installation was done by source through the ports tree. I'm running the following components. 

1x master
3x chunk servers
3x clients
All systems are dedicated hardware. The mfsmount options from /usr/local/etc/mfs/mfsmount.cfg are

mfscachemode=DIRECT
mfsmaster=IP
/storage/sites

I am uploading the testing file through SSH using rsync. The file is uploaded directly to a location under the mfsmount point. 

First test
1: Create a small text file with a single line of text in it on your local computer. Lets call it 'testing.txt'.
2: Use 'rsync' to transfer the file to server 1.
3: Run 'mfsfileinfo testing.txt' on server 1 and 2. Here are the results.

Server 1:
testing.txt:
        chunk 0: 00000000014990AD_00000001 / (id:21598381 ver:1)
                copy 1: 192.168.0.26:9422 (status:VALID)
                copy 2: 192.168.0.27:9422 (status:VALID)

Server 2: 
testing.txt:
        chunk 0: 00000000014990AD_00000001 / (id:21598381 ver:1)
                copy 1: 192.168.0.26:9422 (status:VALID)
                copy 2: 192.168.0.27:9422 (status:VALID)

So far so good. The file shows correctly on all sides. However, if I change the local file and rsync it again, it does not show as updated on the second (or third) server. 

Second test. 
1: Edit the local testing.txt file and change the text. 
2: Rsync the changed file up to the same server over top of the previous file.
3: Run 'mfsfileinfo testing.txt' to test it again. 

Server 1:
testing.txt:
        chunk 0: 000000000149918C_00000001 / (id:21598604 ver:1)
                copy 1: 192.168.0.26:9422 (status:VALID)
                copy 2: 192.168.0.27:9422 (status:VALID)

Server 2:
testing.txt:
        chunk 0: 00000000014990AD_00000001 / (id:21598381 ver:1)
                copy 1: 192.168.0.26:9422 (status:VALID)
                copy 2: 192.168.0.27:9422 (status:VALID)

The file on the second mfsmount point does not change. If I unmount the mfsmount point on the second server and then mount it again, I see the correct file. Again, this only appears to happen when the file name has not changed.

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-01-17 15:36
I did some more testing and this only seems to affect files that are uploaded through SSH, or SFTP. 

The following works. Changing a file this way causes other mfsmount points to show the changes. 

1: Editing a file locally on the server.
2: Editing a file through a SSH connection

The following methods demonstrate the the issue.

1: Uploading through SSH with a program such as rsync.
2: Uploading through SFTP with clients that do not support the "fsync@openssh.com" extension. (EX: Filezilla) 

SFTP works fine if you use a client that supports the "fsync@openssh.com" extensions. For example, using the default command line sftp client on Fedora Gnu/Linux has a '-f' flag that has to be set when connecting. If this done, the file upload is propagated across all the mfsmount points. If you upload without the '-f' flag, only the mfsmount point you upload to will see the changes. 

It appears the mfsmount points are not picking up file changes unless 'fsync' is called by the uploading program. This does not happen through SSH, and requires a special extension with SFTP. 

Is there any way for the mfsmounts to notice when a file changes in those cases?

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-01-22 21:56
My previous statement was wrong. This issue also sometimes happens when files are created directly on the server, though it appears to happen randomly. For additional testing, I edited the same test.txt file on three different mfsmount points on different physical machines. Eventually, after a few edits, I ended up with three different files. Each file had a unique id as shown by mfsfileinfo. 

This only happens when a file changes, but the name does not change. Changing the name of the file in any way causes it to show up correctly across all mfsmount points. I am able to replicate the issue 100% of the time using rsync through ssh, or filezilla. I can replicate it fairly reliable editing local data on the servers. 

Is there any other information I can provide to help resolve this?

**Comment by oxide94** [comment] 2018-01-22 22:28
Hi @k4SsKInGlUJGlnFp,

It is in general related to FreeBSD dentry cache issues in kernel / FUSE implementation we discovered.

I will try to elaborate this week.

Thanks,

Best regards,
Peter / MooseFS Team

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-01-23 00:22
Hello, 

Thank you for your reply. I've tested setting the sysctl **vfs.fuse.lookup_cache_enable=0** and that does stop the issue from happening. It also causes performance to slow down significantly. 

Please let me know if there is anything else I can test, or try and help with.

Thank you

**Comment by xandrus** [comment] 2018-01-23 07:14
Hi,
I would like to add that there the problem is still present in Fuse kernel part. 
You can easily corrupt your data because during append operation position is set incorrectly.

We have to inform FreeBSD developers about all this problems.

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-01-23 13:56
Hi @xandrus 

Thank you for the heads up. Can you link to the FreeBSD bug report once it exists?

**Comment by oxide94** [comment] 2018-01-25 18:18
Hi @k4SsKInGlUJGlnFp,

We haven't issued a bug report on FreeBSD Bugzilla, we are going to to it soon. As we discovered like 4-5 issues, we need to isolate every single as a separate scenario or even prepare a short code snippet for FreeBSD Team, and unfortunately it will take some time to prepare all the necessary info.

We will let you know once issues are posted on the Bugzilla.

Thanks,

Best regards,
Peter / MooseFS Team

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-02-01 14:44
Hello, 

Is there any type of temporary workaround for these bugs? If not, is there anything that I can do to help  with resolving them? I am still seeing the issue after upgrading to 3.0.100. 

Thank you

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-02-28 22:55
Hello, 
Is there any update on this?

**Comment by oxide94** [comment] 2018-03-01 00:50
Hi @k4SsKInGlUJGlnFp,

I am sorry for no answer on our side. As I mentioned previously, this is one of issues in FreeBSD kernel / FUSE we discovered which has impact on MooseFS. For all other issues we were able to overcome them with a workaround inside MooseFS, but for this particular one it is not possible (this is why v. 3.0.100 doesn't change anything in this matter).

Unfortunately, we haven't posted these issues on FreeBSD Bugzilla yet, because we have been very busy with MooseFS 4.x tests and fixes recently. I hope this month (i.e. march) we will do it and keep fingers crossed FreeBSD guys will fix them :)

We didn't forget about this issue and we want it to be fixed, so we do our best to make it happen. I will be updating you here about future progress.

Thanks for understanding,

Best regards,
Peter / MooseFS Team

**Comment by oszafraniec** [comment] 2018-03-01 09:26
I know this is not a solution, but as a matter of feedback... As a long user of FreeBSD we have migrated all server to Ubuntu in my company and I have to tell you... All problems are gone. We had a lot of problems 2 years ago with FreeBSD mounts @ MooseFS (@oxide94 knows them very well). We have no problems with it using Ubuntu. And performance sky-rocketed at least x2 just because of system switch (same hardware, same apps), both @moose and other apps.

Sad, but true :(

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-03-01 14:51
Hello @oxide94 

Thank you for your response. We intend to fund developer time at the FreeBSD project to fix these issues. As soon as the bug reports are in, I'll be reaching out to available parties to push forward a resolution.

@oszafraniec 
Thank you for your feedback. I'll keep it in mind if we continue to have issues.

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-04-02 16:56
Hello @oxide94,
 
Is there any update on this?

**Comment by oxide94** [comment] 2018-04-16 23:03
Hi @k4SsKInGlUJGlnFp,
thanks for bumping this thread. Yes, there are good news! :) We are in progress of isolating this issue and other issues related to kernel/libfuse on FreeBSD to make it clear for FreeBSD devs and it is almost finished. Once finished and posted to the Bugzilla I will definitely remember to let you know here.

Thanks,
Best regards,
Peter / MooseFS Team

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-04-17 00:10
Hi @oxide94 

Thank you for the update. I'll be sure to follow up on the bug report to try and encourage development to fix this.

Thank you

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-05-10 00:52
Hello @oxide94 

Is there any update on this? I am not seeing any FreeBSD bug reports.

**Comment by nbari** [comment] 2018-06-16 16:52
Hi @oxide94 any update on this, [has it been reported](https://www.freebsd.org/support/bugreports.html) or fixed on the coming FreeBSD 11.2?

**Comment by k4SsKInGlUJGlnFp** [comment] 2018-06-29 14:29
Hello, 

This issue prevents using MooseFS entirely. Is there anything we can do to help move towards a resolution?

**Comment by oxide94** [comment] 2018-08-01 12:56
Hello @k4SsKInGlUJGlnFp, @oszafraniec, @nbari,

I would like to inform, that we have reported this and other issues on FreeBSD Bugzilla. Please find URLs below. Any help on resolving them is appreciated.

This issue:
* [FUSE] [BUG]: Attributes caching issue:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230258

Other issues:
* [FUSE] [BUG]: File close (release) issue:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230259
* [FUSE] [PERFORMANCE]: Performance issue (I/O block size): https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230260

Thank you,

Best regards,
Peter / MooseFS Team

**Comment by oxide94** [comment] 2019-02-11 17:31
Hello,
Just wanted to let you know that there is some progress on this issue. For more information please refer to [[FUSE] [BUG]: Attributes caching issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230258) on FreeBSD Bugzilla.

Thanks,
Piotr

**Comment by oxide94** [comment] 2019-02-16 01:45
Hi all,
@cemeyer just pushed a few commits which close [[FUSE] [BUG]: Attributes caching issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230258).

Adding just for reference:
* "FUSE: The FUSE design expects writethrough caching":
https://github.com/freebsd/freebsd/commit/bb3c594db5343e08a9c8d657c00912be8eecba87 / https://github.com/freebsd/freebsd/commit/a4d515646c68b8ed198bee0406e8cf0f94ea417a
* "FUSE: Respect userspace FS "do-not-cache" of file attributes": https://github.com/freebsd/freebsd/commit/fde561aa6ecded8a70bb2d9a44dbb69baf9b953d
* "FUSE: Respect userspace FS "do-not-cache" of path components": https://github.com/freebsd/freebsd/commit/6ce2686c1514bbb35834df3eb4f91dc5a1c2675b
* "FUSE: Refresh cached file size when it changes (lookup)": https://github.com/freebsd/freebsd/commit/d5f3fe6662c5c2ec26bc10f9bf6e7837e6b12797
* "FUSE: Only "dirty" cached file size when data is dirty": https://github.com/freebsd/freebsd/commit/58697545cbea450d9114071ec7dd3ca3f1994b9b (related)

There were also several related issues identified:
* [[FUSE]: Missing real support for attr/dentry cache timeouts](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235773)
* [[FUSE]: Need to evict invalidated cache contents on fuse_write_directbackend()](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235774)
* [[FUSE]: Reuse cached attributes, when available and valid](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=235775)

Also related issue: https://github.com/vgough/encfs/issues/315.

Thanks for @cemeyer, @benrubson and @acid-maker for all the valuable input and time spent on this, we appreciate it!

Best,
Piotr / MooseFS Team

**Comment by cemeyer** [comment] 2019-02-16 04:01
Hi everyone, sorry about the delay on this.  I'm hoping Piotr et al can test these changes and verify that things are (somewhat) improved — we know there is other work to do, but some of the most egregious issues should be resolved by these changes.

The other thing to keep in mind is that these fixes are only in FreeBSD head and not yet in stable/12 or stable/11.  I don't work on Freebsd-stable myself, but in the past, MarkJ@FreeBSD has backported some FUSE fixes to stable branches and may be willing to facilitate that if you ask.

**Comment by chogata** [comment] 2024-09-20 10:23
Both FreeBSD and MooseFS had a lot of changes since this issue arised. Please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).

**Closed** 2024-09-20 10:25 UTC
Labels: libfuse/kernel, upstream/fuse, fix committed / please test
