### ISSUE TITLE
[feature] erasure-coding

### ISSUE THREAD

**Issue by onlyjob** [moosefs/moosefs#8] opened 2016-03-19 05:41 UTC
Erasuse coding is a space-efficient yet reliable way to store data in distributed manner.
It is already implemented in Ceph, LizardFS and some other storage systems.

See also https://github.com/lizardfs/lizardfs/issues/207

**Comment by nrm21** [comment] 2016-04-13 06:40
+1

**Comment by acid-maker** [comment] 2016-04-22 05:37
@nrm21 of course we will add erasure coding in the upcoming (4.0) version, but still I don't see how it might resolve your problem. Erasure coding still will have its redundancy level to keep, and after chunkserver disconnection replication will begin.

I think that you need something else. You probably need option to allow temporary undergoals (or "under-redundancy-level" in EC). It can be added independently from EC.

I don't think that allowing temporary undergoals is a good idea. The problem is that in case of failure replication should begin as soon as possible. This is why we implemented "maintenance mode". Maybe this mechanism should be somehow improved.

This is my idea:

1. Chunkserver during graceful stop just before disconnection from master will send command that will turn on "temporary maintenance mode".

2. When chunkserver with "temporary maintenance mode" will connect again then master will turns off "temporary maintenance mode".

With such approach you will be able to restart chunkservers, or do some quick maintenance without changing anything in the master server. In such case replication will not start, but during real server failure chunkserver will not disconnect gracefully and in such case replication will start immediately.

What do you think?

**Comment by nrm21** [comment] 2016-04-22 15:57
That sounds like it could work just as well.

Just something for the quick reboot or other going offline temporarily.  Maybe with a user configurable timer that if exceeded (and the device still hasn't returned) would turn off maint mode and start replication.  This could cut down on the false start replications.

**Comment by tehbenneh** [comment] 2016-04-22 16:02
I would love this.

**Comment by kiatoa** [comment] 2016-04-22 18:18
Related to this, I think an option to make removing extra chunks more lazy
would be good.

Scenario is that a disk goes offline and gets replicated then comes online
and gets removed, then it happens again. All this churn would be reduced by
more lazy removal of extra chunks.
On Apr 22, 2016 8:57 AM, "Nathan Morrison" <notifications@github.com> wrote:

That sounds like it could work just as well.

Just something for the quick reboot or other going offline temporarily.
Maybe with a user configurable timer that if exceeded (and the device still
hasn't returned) would turn off maint mode and start replication. This
could cut down on the false start replications.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/moosefs/moosefs/issues/8#issuecomment-213489274>

**Comment by acid-maker** [comment] 2016-04-25 07:52
We've changed the original topic, so I've created new issue <#9> for this new feature (automatic maintenance mode).

**Comment by zjay1987** [comment] 2016-07-19 10:39
Hey @acid-maker , is there any release schedule for dev version of 4.0? Can't wait for that:)

**Comment by oszafraniec** [comment] 2017-03-21 13:22
@acid-maker Any update? Deadline? Prediction? Can't wait to take is for a test drive ;)

**Comment by yinjiawind** [comment] 2017-07-18 01:37
@acid-maker 
In MooseFS official website, it seems that MooseFS4.0 is OK!  Is there any release schedule to github  for dev version of 4.0?

**Comment by onlyjob** [comment] 2018-08-27 03:53
For now Erasure Coding seems to be a feature of non-free _MooseFS Pro_ v4... :(

It would be great to allow users of free _MooseFS_ to have access to that feature.

**Comment by guestisp** [comment] 2018-08-27 05:34
V4 is free and EC is available

**Comment by jkiebzak** [comment] 2018-08-27 14:18
Where is this? https://moosefs.com/download/#current only shows V3...

**Comment by guestisp** [comment] 2018-08-27 14:27
Ask in the mailing list.
Actually is in beta

**Comment by onlyjob** [comment] 2018-08-28 09:55
@guestisp, please don't mix up _zero price_ and _free_. _Pro_ edition is non-free, i.e. _proprietary_: https://moosefs.com/license-pro/

**Comment by guestisp** [comment] 2018-08-28 10:50
@onlyjob that's about v3.
v4 is different, AFAIK, is totally open-source with all features (and I have a v4 as testing with *all* features). Only support is under payment.

**Comment by oszafraniec** [comment] 2018-08-28 11:14
@guestisp , as far as I know (and we also have v4 with all features available FOR TESTING!) there is still now official information about v4 license scheme. I know we all would like to see EC in community edition, but for now this is only our wishful thinking ;)

**Comment by onlyjob** [comment] 2018-08-28 11:15
It is not open source when its sources are not open. :) Where are the sources? "source code" link at moosefs.com points here, where I can not find sources of v4. I'm not interested in binaries...

**Comment by guestisp** [comment] 2018-08-28 11:18
I've talked with MooseFS developers
It will be published ad open source when it's stable

**Comment by borkd** [comment] 2018-09-06 21:10
@guestisp - show me the code, or it is all hype and hearsay.

Yes, v4 has been available for early testing with all new bells and whistles, and yes, core developers promised to gift the HA feature to the community version. This in itself is a major step forward, and I look forward to torturing and finding weak spots in MooseFS v4+ in the years to come.

Beyond hearsay, it is hard, if not impossible, to guess what set of features will be available for public consumption when v4 branch is pushed, and what features will be reserved for paying customers. That business decision has not been announced to the best of my knowledge.

**Comment by hradec** [comment] 2019-01-07 08:42
I'm quite pleased to see how MooseFS is way beyond LizardFS these days... kudos to you guys! 

I was happily surprised to see the storage-classes mechanisms, which basically sorts out a big problem we have today with LizardFS, which is mixing fast throughput with redundancy and safety.

Unfortunately, I really need erasure-coding goals (or storage classes) since we have loads of stored data that needs to be accessed sporadically but still need to be online. (storage in Brazil is still expensive)

So, unfortunately we have to hold until MooseFS has EC(D,P) to move from LizardFS to MooseFS!

so, +1 from me to erasure-coding!

**Comment by onlyjob** [comment] 2019-01-07 12:38
These days LizardFS team is not even fixing bugs any more... :(
Dynamics is so bad that they've fixed no more than few issues in the last 12 months. Their priorities are questionable; lack of progress and presence of serious bugs make me worry for the future of the project. LizardFS is finished unless situation drastically changes in the near future.

It is great that MooseFS remains an active alternative.
Unfortunately state of packages is far from ideal but I can only blame myself for it...

**Comment by zcalusic** [comment] 2019-01-07 12:48
So, we have a very interesting situation here:

- LizardFS has erasure coding, but is not maintained anymore
- MooseFS is well maintained, but no support for erasure coding

Only time will tell...

I always thought that rewriting MooseFS was a waste of resources, then again LizardFS did some progress which is not yet available in MooseFS.

I guess I'll just stay subscribed to this ticket... :smile:

**Comment by guestisp** [comment] 2019-01-07 16:10
EC in MooseFS is **already** available with the open-source v4.
The real question is: when this new version will be released ? @acid-maker  Any updates about this ?

I've tested it for a while and it's absolutely awesome, it's really a scale-out storag, with a perfectly working HA solution out of the box. Just add two or more master server and they will be synced automatically with automatic failover. Absolutely awesome. No need for external scripts like with LizardFS. Just add 2 or more masters pointing to the same IP and you are ready to go.

**Comment by guestisp** [comment] 2019-01-07 16:13
> Unfortunately state of packages is far from ideal but I can only blame myself for it...

I think you should add MooseFS packages on debian like you did with LizardFS. As LizardFS seems to be a dead project (i've seen that many month ago, that's why i've never used that deeply), adding the MooseFS alternative would be great for anyone looking for a stable SDS. Then, when v4 will be realease, an upgrade would be easy like an `apt-get update && apt-get upgrade`

**Comment by onlyjob** [comment] 2019-01-08 02:32
I can only maintain one system...
To me _MooseFS_ is not an option until erasure coding becomes mainstream...

**Comment by borkd** [comment] 2019-01-08 02:50
> EC in MooseFS is **already** available with the open-source v4.

Unless something changed in the last 24 hours, contrary to what @guestisp keeps repeating, EC is only available in the v4 Pro RC (commercial, not open-source). Adding "PR welcome" tag until existing EC makes it into the community version from Pro v4, or someone submits a PR with a safe and decently performing implementation. Not a fan of duplicating efforts, but that _could_ prompt the developers to simplify and push the safest and faster of the two into the community branch sooner rather than later.

**Comment by onlyjob** [comment] 2019-02-21 00:04
I think it is a strategic mistake of the MooseFS team to withhold erasure coding from the community.
Three of the closest competitors (LizardFS, RozoFS, Ceph) have erasure coding.

How many people will decide to use try MooseFS last because of lack of this feature?
MooseFS needs to grow the community and get more commercial customers through greater popularity. IMHO enterprise-only master fail-over is already good enough incentive for paying customers.
To be competitive MooseFS should have EC in the community edition.

**Comment by jkiebzak** [comment] 2019-02-21 00:29
+1

>

**Comment by onlyjob** [comment] 2019-02-21 08:06
If I had to implement Erasure Coding for MooseFS, I would have taken [Mojette Transform](https://en.wikipedia.org/wiki/Mojette_Transform) implementation from [RozoFS](https://github.com/rozofs/rozofs) - it is licensed under [compatible license](https://github.com/rozofs/rozofs/blob/master/COPYING) (GPL-2).

Mojette Transform is the fastest and most efficient flavor of EC.

**Comment by BradFD** [comment] 2020-01-22 01:24
All this talk of Moosefs v4. Where can I download v4 to try it? Thank you.

**Comment by foundObjects** [comment] 2020-01-23 02:16
It's 2020 now; any news on a 4.0 open source release? I'd love to demo this on my cluster.

**Comment by chogata** [comment] 2020-01-27 10:26
Our priorities right now lie with version 3 and resolving all the reported issues. Since we would like to give the same attention to version 4 when it gets released, we decided not to do both of those things at the same time.

Nevertheless, if you are serious about testing version 4, drop us a note [here](https://moosefs.com/#contact) with a brief explanation why you would like to test it. We'll see if we can do something for you

**Comment by chogata** [comment] 2024-09-20 10:01
EC format is now available in MooseFS 4 - please, upgrade and test. If comments are needed, please open a new issue or discussion (whichever is appropriate for the info you want to post).

**Closed by chogata** 2024-09-20 10:01 UTC
Labels: feature
