### ISSUE TITLE
force changing builtin goal/sc seems not respect chunkserver label

### ISSUE THREAD

**Issue by tclh123** [moosefs/moosefs#134] opened 2018-08-08 09:27 UTC
The builtin goal 3 has labels "*, *, *". I force change it to "B, B, B". The wrong labels replication seems not occurred.

**Comment by borkd** [comment] 2018-11-20 15:10
This issue seems to be related to #146

**Comment by acid-maker** [comment] 2018-11-27 06:48
Yes. I've just checked the code and I can confirm that such a bug exists. There are conditions that treat classes 1-9 little differently. It should be easy to fix.

**Comment by acid-maker** [comment] 2018-11-27 12:16
fixed by 8ab9f05098f8abcda75ea83f9552154b50fe3b6c

**Closed** 2018-12-05 18:21 UTC
Labels: confirmed bug, duplicate, need more info
