### ISSUE TITLE
Can not set suid option using "mount -t moosefs ..."

### ISSUE THREAD

**Issue by stevew-Purdue** [moosefs/moosefs#101] opened 2018-04-03 16:19 UTC
We use systemd for mounting our MooseFS file systems and I have one file system that needs to permit SUID executables.  I've found that using "mount -t moosefs ... -o suid" (which is the form used by systemd) doesn't actually mount a file system with SUID permission:
- root@test1:/mnt# mount sb-data:/apps/linux /mnt/apps -t moosefs -o suid
- mfsmaster accepted connection with parameters: read-write,restricted_ip,admin ; root mapped to root:root
- root@test1:/mnt# grep /mnt/apps /etc/mtab
- sb-data:9421 /mnt/apps fuse.mfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other 0 0

If I use the "mfsmount ... -o suid" form, then it works:
- root@test1:/mnt# mfsmount sb-data:/apps/linux -o suid /mnt/apps
- mfsmaster accepted connection with parameters: read-write,restricted_ip,admin ; root mapped to root:root
- root@test1:/mnt# grep /mnt/apps /etc/mtab
- sb-data:9421 /mnt/apps fuse.mfs rw,nodev,relatime,user_id=0,group_id=0,allow_other 0 0

Also, other options seem to work fine with the "mount -t moosefs ..." form but not the suid option.  We are using version 3.0.97 of moosefs-client but I also tried this with version 3.0.100 and it fails for that version as well.

Thanks,
Steve

**Comment by stevew-Purdue** [comment] 2018-04-03 19:54
It actually turns out to be a problem with the mount command.  I replaced the symbolic link of /sbin/mount.moosefs ==> /usr/bin/mfsmount with a simple shell script that echoed its command line parameters before executing /usr/bin/mfsmount.  To my surprise, the "-o suid" parameter had been stripped off by the mount command before mount.moosefs is executed.

I'm guessing that mount doesn't pass options that are part of the kernel defaults, usually "rw, suid, dev, exec, auto, nouser, async" according to the mount man page.  I tried the "-o nodev" option and it was passed to mount.moosefs but "-o dev" was not. This adds some support for my theory of what mount is doing.

If this is truly the case, then maybe it's a good idea for mfsmount to try to always mimic the kernel defaults for mount.  Or, better yet, mount should pass ALL options and not try to be so smart!

As a work-around, I can create a special mfsmount config file which includes the suid option and pass that on the mount command line:
- mount sb-data:/apps/linux /mnt/apps -t moosefs -o mfscfgfile=/etc/mfs/mfsmount-apps.cf

I'd like to hear from anyone who has more insight into this problem, though.

**Comment by acid-maker** [comment] 2018-04-17 05:38
We do not add "nodev" or "nosuid" - those settings are "fuse" defaults - this is why by default moosefs mounts are mounted with "nodev" and "nosuid" - in my opinion if this causes any troubles then it should be fixed in the fuse, not moosefs.

I'm not sure if adding "suid" and "dev" to DEFAULT_OPTIONS is a good idea. If you add then "nosuid" or "nodev" then kernel will get positive and negative option together - I'm not sure what will happen.

**Comment by stevew-Purdue** [comment] 2018-04-17 15:50
As I see it, the problem exists between the system mount command and mfsmount, not between mfsmount and fuse mount.  In fact, everything works as expected between mfsmount and fuse mount.

When passed an option which is the same as a default for the system mount (like "-o suid"), the system mount command decides not to pass that option on to the mount helper (mount.moosefs/mfsmount in our case) since it is a default option.  This would not be a problem if the defaults for mfsmount were the same as the defaults for the system mount.

There are only two solutions that I can see:
1)  modify system mount (understandably outside of your responsibility!) to always pass options specified on the command line, even if they match what is considered a default option by system mount, or
2)  modify mfsmount to always have the same default options as the system mount.  This would also imply some change to the interface between mfsmount and fuse mount to make sure that any default fuse mount options (like nosuid and nodev) are overridden when necessary.

And maybe until one of these two solutions comes about, the documentation should note that neither the "suid" option nor the "dev" option will work as expected when the "mount ..." command is used but will work when "mfsmount ..." is used.

**Comment by acid-maker** [comment] 2018-05-16 05:53
The problem is inside fuse (probably kernel side). When I do not send anything to fuse it assumes that mountpoint should be mounted without 'suid' and 'dev'. As I understand this behaviour is dirrerent from  behaviour of other filesystems. You should probalby mention this discrepancy in Fuse project.

In the meantime I may add simple fix for this in mfsmount - if there is no 'nosuid' explicitly defined then I will add 'suid' option to fuse options inside mfsmount (the same with 'nodev').

Modifying system mount is not a good idea. Modifying mfsmount

**Comment by oxide94** [comment] 2018-05-16 12:05
Hi @stevew-Purdue,

After considering all pros and cons we believe, that enabling `suid` and `dev` options by default is not the best idea, because it may lead to some security breaches. The best and the most secure idea, we think, is to add extra parameters `mfssuid` and `mfsdev` which would be 1) passed-through OS mount, 2) parsed by `mfsmount`, changed to `suid` and `dev` on the fly respectively and then sent to kernel.

What do you think?

Best regards,
Peter / MooseFS Team

**Comment by stevew-Purdue** [comment] 2018-05-16 13:42
Hi Peter,


Your solution would work well for me; thanks for considering this issue and proposing a workable solution.


?Kind regards,

Steve


________________________________

**Closed** 2018-05-17 07:12 UTC
Labels: feature, libfuse/kernel, question
