### ISSUE TITLE
Space reservation

### ISSUE THREAD

**Issue by pflorczyk** [moosefs/moosefs#133] opened 2018-07-25 13:49 UTC
It would be really helpful if we could declare some space reservation that is available for replication but hidden from end users (doesn't show up in df).
This should prevent space overcommiting in situations when one or more chunkservers go down.

**Comment by oszafraniec** [comment] 2018-07-26 10:45
Doesn't setting up quota do what you want, from end-user/df perspective?

**Comment by pflorczyk** [comment] 2018-07-27 12:53
Not exactly. First of all you need to have quota enabled and even then quota is really unusable when you have snapshots (:speak_no_evil::sweat_smile:). When any chunkserver goes down you loose not only free space it provided. You also have to ensure that there is free space available for chunks it was holding (sooner or later they will start to replicate on other chunkservers).

**Comment by oszafraniec** [comment] 2018-07-27 13:07
Yes, I do get it that you want to have some spare space available always for replication in case of chunkserver going down. It even can be automated as a spare space should be at least the size of biggest chunkserver you have (used space, not total). It could be also indicated on mfs.cgi by showing free space in red if it's too short to handle biggest chunkserver failure. Anyway, nice feature :)

**Comment by oxide94** [comment] 2018-11-09 21:55
@pflorczyk: This feature has been implemented in commit 632b26c16ffd0e23ce0986ea9b1cbd946468d211 :)

Thanks for the idea!

Best regards,
Peter / MooseFS Team

**Comment by borkd** [comment] 2018-11-20 15:14
"solved! :)" means the issue can be closed as resolved, or does it still need some work/documentation/testing?

**Closed** 2019-01-08 02:53 UTC
Labels: documentation, feature, solved! :)

**Comment by oxide94** [comment] 2019-01-08 08:54
@borkd: My idea on "solved! :)" was to easily indicate the issue is resolved, however we want to keep it open for a while because of some reason (a good example is issue no. 146: It is resolved but held as open until 3.0.104 is not released officially).

Best,
Peter / MooseFS Team

**Comment by borkd** [comment] 2019-01-08 14:32
@oxide94 - "solved" is a bit ambiguous. What do you think about replacing it with:
- "fix committed, please test"
- "review documentation"
and then, once documented fix makes it into tagged releases close the original issue?

**Comment by oxide94** [comment] 2019-01-08 15:32
I think they're good.

However there are some issues which are unrelated to any changes in MooseFS sources, for example tickets like questions from Users etc. and if such a ticket is not closed for some reason it may be good to have a label indicating that the question / issue is resolved.

Best,
Peter / MooseFS Team

**Comment by borkd** [comment] 2019-01-10 03:08
If it is a _**valid**_ question that should, but could not be answered by documentation or FAQ, then the documention has a bug which can be fixed by PR or a commit.

Updating FAQ, documentation, and/or message strings within the code will take similar amount of time as explaining this within the ticket. Less duplicate work on stuff that nobody loves to do?

**Comment by oxide94** [comment] 2019-01-10 12:37
True.
Peter
